language: python
cache: pip
dist: bionic

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<2.3"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install -U $DJANGO
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint
  - jslint django_loci/static/django-loci/js/*.js

install:
  - pip install -e .

script:
  - |
      openwisp-utils-qa-checks \
      --migration-path \
        "./django_loci/migrations \
        ./django_loci/tests/testdeviceapp/migrations" \
      --migration-module django_loci
  - pytest --cov=django_loci
  - coverage run -a --source=django_loci runtests.py

after_success:
  coveralls
